### PR TITLE
Misc. updates, some changes to synchronize w/ @jhgoebbert

### LINKED ISSUE #2: Update logo / icon

### PR DESCRIPTION
**Pull request by sk1p**
+ tweak timeout
 + log startup command
 + update icon (closes #2)
 + update README

Co-authored-by: Jens Henrik Goebbert <j.goebbert@fz-juelich.de>

### CODE REVIEW

**Comment by sk1p** [comment]
@jhgoebbert I've incorporated some changes from your repo here - is this sufficient to make the integration at JSC work? Does the location of the configuration file work, or does it need adjustments?

**Review by jhgoebbert — CHANGES_REQUESTED** [review]
`config_path = os.path.join(sys.prefix, "etc", "libertem_jupyter_proxy.json")`
I would not force the need for a system-wide installation of LiberTEM. On our clusters, for example, the software must be installed even without root privileges.
One solution could be to check for a system variable like LIBERTEM_ROOT here and use it instead of `sys.prefix` if it exists.

`shutil.which(executable):`
This line forces to have the LiberTEM software in the PATH for each and every user who uses the system-wide installation of a JupyterLab (which has the LiberTEM-extension installed) on a multi-community cluster.
Again this assumes to some extend that LiberTEM is installed system-wide and not loaded on demand. But conflicts between different software tools often do not allow to have all and every software in PATH at the same time on larger clusters. One solution could be to check for a wrapper-script and call that one, if it exists. There one could update PATH when needed before calling libertem-server.

`"X-Api-Key": token,`
I do not really understand, how this token is checked. On server-side you create a token and embedd that token into the HTML-header. Then the HTML-page (including the token) is passed to the browser. How does that increase the security? ... am I getting something wrong here?

**Comment by sk1p** [comment]
Hi @jhgoebbert, thanks for the review!

> `config_path = os.path.join(sys.prefix, "etc", "libertem_jupyter_proxy.json")`
> I would not force the need for a system-wide installation of LiberTEM. On our clusters, for example, the software must be installed even without root privileges.
> One solution could be to check for a system variable like LIBERTEM_ROOT here and use it instead of `sys.prefix` if it exists.

`sys.prefix` is not necessarily the prefix of the system-wide Python installation - in most cases (i.e. with a virtualenv or in a conda installation) this points at the root of the Python environment. Adding an environment variable `LIBERTEM_ROOT` as a preferred prefix sounds easy enough, I'll add this. 

> `shutil.which(executable):`
> This line forces to have the LiberTEM software in the PATH for each and every user who uses the system-wide installation of a JupyterLab (which has the LiberTEM-extension installed) on a multi-community cluster.
> Again this assumes to some extend that LiberTEM is installed system-wide and not loaded on demand. But conflicts between different software tools often do not allow to have all and every software in PATH at the same time on larger clusters. One solution could be to check for a wrapper-script and call that one, if it exists. There one could update PATH when needed before calling libertem-server.

This is only supposed to be a fallback, if there is no configuration that specifies otherwise - this is not for the system-wide installation use-case, but for the simple case that LiberTEM is installed in the same environment as jupyter{lab,hub,notebook}. For example, this is the case when installing locally, or when running [in MyBinder](https://mybinder.org/v2/gh/LiberTEM/LiberTEM-jupyter-proxy/master?urlpath=lab)

I would prefer to have explicit configuration in case of using a wrapper script, which allows you to point to any script anywhere, and doesn't constrain you to some fixed script name.

> `"X-Api-Key": token,`
> I do not really understand, how this token is checked. On server-side you create a token and embedd that token into the HTML-header. Then the HTML-page (including the token) is passed to the browser. How does that increase the security? ... am I getting something wrong here?

`request_headers_override` adds an *HTTP* request header, it doesn't change the response HTML (most responses aren't even HTML). Before a response is even generated, this HTTP header is checked by [a middleware](https://github.com/LiberTEM/LiberTEM/blob/7c2d5029a62e6a4c2f351262d8e3940d53a33826/src/libertem/web/server.py#L62) to match the one given in `--token-path`. Does this clear things up?

**Comment by jhgoebbert** [comment]
> > `shutil.which(executable):`
> This is only supposed to be a fallback, if there is no configuration that specifies otherwise [..]
Sorry. Sure, this is just a fallback. Then it looks perfekt to me.

> > `"X-Api-Key": token,`
> > I do not really understand, how this token is checked. [..]
> `request_headers_override` adds an _HTTP_ request header, it doesn't change the response HTML [..] Does this clear things up?
Yes, thanks. Sounds good.

**Review by jhgoebbert — APPROVED** [review]
That looks good to me.  

(anyway, for our clusters I still need to patch it, as I think we shall allow to show the LiberTEM extension in JupyterLab without need to load the LiberTEM software module in advance - this shall happen when the user clicks on the launcher-icon. But probably that is too specific to be considered here)

**Comment by sk1p** [comment]
> That looks good to me.

Thanks again for the review!

> (anyway, for our clusters I still need to patch it, as I think we shall allow to show the LiberTEM extension in JupyterLab without need to load the LiberTEM software module in advance - this shall happen when the user clicks on the launcher-icon. But probably that is too specific to be considered here)

Ok, feel free to open a PR - maybe we can figure something out, so you don't have to maintain another fork

**Pull request merged**
